#! /bin/bash

DOCKER_REGISTRY_URL = $DOCKER_REGISTRY_URL
DOCKER_REGISTRY_USER_NAME=$DOCKER_REGISTRY_USER_NAME
APP_NAME=$APP_NAME

BUILD_NUMBER=${BUILD_NUMBER:-dev}
VERSION=${MAJOR_VERSION}.$BUILD_NUMBER

FULL_TAG = $DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USER_NAME/$APP_NAME:$VERSION
FILE_NAME = $APP_NAME-$VERSION

echo "Building Docker image..."
docker build --tag $FULL_TAG .

if [$DOCKER_REGISTRY_URL != 'localhost']; then
  echo "Pushing Docker image to Resgitry..."
  docker push $FULL_TAG
fi
